#!/bin/bash

#para lanzarlo desde local, necesario par de claves rsa (consultar https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion/wiki)
#ssh x@ip_remota 'bash -s' < docker_remoto

#para actualización(necesario backup BD o BD en local. No procede en la asignatura)
#sudo rm -R decide-ganimedes-autenticacion/
#sudo docker rm$(sudo docker ps -a -q)
#sudo docker rmi$(sudo docker images -q)

git clone https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion.git

sudo apt-get update
sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get -y install docker-ce
sudo snap install docker
cd decide-ganimedes/docker
sudo docker-compose up -d

