#!/bin/bash

#para lanzarlo desde local es necesario par de claves rsa (consultar https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion/wiki)
#ssh user@ip_remota 'bash -s' < docker_remoto


sudo rm -R decide-ganimedes-autenticacion/

git clone https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion.git

sudo apt-get update
sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get -y install docker-ce
sudo snap install docker
cd decide-ganimedes-autenticacion/docker
#para actualización real sería necesario backup BD o BD en local o no borrar todo
sudo docker rm $(sudo docker ps -a -q)
sudo docker rmi $(sudo docker images -q)

sudo docker-compose up -d



